@sid = 6f392c3b-c99a-11ec-a2b3-00d861a99de2

@did = 6639e056-c9d8-11ec-b85f-00d861a99de2
@cid = 63f62914-c9d8-11ec-b85f-00d861a99de2
@mid = 2f71d61b-c9d9-11ec-b014-00d861a99de2
POST http://localhost:9000/svc/{{sid}}/api/v1/devs

{
    "did": "{{did}}",
    "dname": "DEVICE-B-UUID",
    "cid": "{{cid}}",
    "sname": "devicemanagera"
}

GET http://localhost:9000/svc/{{sid}}/api/v1/devs/list

GET http://localhost:9000/svc/{{sid}}/api/v1/status

POST http://localhost:9000/svc/{{sid}}/api/v1/status

{
    "did": "{{did}}",
    "dname": "DEVICE-A-UUID",
    "cid": "{{cid}}",
    "name": "measured data",
    "status": {
        "fan": false
    }
}

GET http://localhost:9000/svc/{{sid}}/api/v1/status
did: {{did}}


POST http://localhost:9000/svc/{{sid}}/api/v1/status/{{mid}}

{
    "did": "{{did}}",
    "status": {
        "fan": false,
        "lamp": false
    }
}


POST http://localhost:9000/svc/{{sid}}/api/v1/status/{{mid}}

{
    "did": "{{did}}",
    "cid": "{{cid}}",
    "status": {
        "fan": false,
        "lamp": false
    }
}

PUT http://localhost:9000/svc/{{sid}}/api/v1/status/{{mid}}

{
    "did": "{{did}}",
    "status": {
        "Temp": 100,
        "Humidity": 10
    }
}

GET http://localhost:9000/svc/{{sid}}/api/v1/status
did: {{did}}

POST http://localhost:9000/svc/{{sid}}/api/v1/devs

{
    "did": "1ad73898-fe73-4053-8bbd-29a6ac6c927B",
    "dname": "DEVICE-A-UUID",
    "cid": "8971e21d-4800-47e4-b50e-691e28d2f701",
    "sname": "devicemanagera"
}

POST http://localhost:9000/svc/{{sid}}/api/v1/status

{
    "did": "1ad73898-fe73-4053-8bbd-29a6ac6c927B",
    "dname": "DEVICE-B-UUID",
    "cid": "8971e21d-4800-47e4-b50e-691e28d2f701",
    "status": {
        "fan": false,
        "lamp": false
    }
}

GET http://localhost:9000/svc/{{sid}}/api/v1/status

GET http://localhost:9000/svc/{{sid}}/api/v1/status/{{mid}}

GET http://localhost:9000/svc/{{sid}}/api/v1/status/b9539103-c879-11ec-a28f-5254009af0ec